workspace:
  base: /go
  path: src/github.com/keymetrics/pm2-io-apm-go

pipeline:
  tests:
    image: golang:latest
    commands:
      - go get -t -v
      - go get gopkg.in/h2non/gock.v1
      - go test -v -coverprofile=coverage.txt -covermode=atomic $(go list ./...)
      - bash <(curl -s https://codecov.io/bash) -t $$codecov_token
      - go build

  slack:
    image: plugins/slack
    channel: ci
    when:
      status: [ success, failure ]
    template: |
      {{#success build.status}}
        pm2-io-apm-go {{ build.commit }} on {{ build.branch }} succeeded @{{ build.author }}
      {{else}}
        pm2-io-apm-go build {{ build.number }} on {{ build.branch }} failed @{{ build.author }}
      {{/success}}
      see {{ build.link }}
    secrets: [ slack_webhook ]